version: '3'
services:
  hub:
    image: selenium/hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
    volumes:
      - /dev/shm:/dev/shm

  firefox:
    image: selenium/node-firefox
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
    volumes:
      - /dev/shm:/dev/shm
